### ISSUE TITLE
Knots with curves other then linear

### ISSUE THREAD

**Issue by danielverejan** [pbeshai/d3-interpolate-path#7] opened 2016-11-17 07:47 UTC
Hi there, I tried the plugin for two sets of data with a different count points and it works like magic when the line uses linearCurve but creates knots when using it on curves other then linear.
![knots](https://cloud.githubusercontent.com/assets/7072732/20380426/abc8dbac-acaa-11e6-92bf-e4c775a7181f.png)
Is it a limitation of how paths works?

**Comment by pbeshai** [comment] 2016-11-17 14:15
Whoa those are pretty wild. If you could paste the `d` attribute for one of those paths before and after the interpolation that would be helpful. The other day I came up with an alternative approach I wanted to make available as an option which might fix it, but it would be helpful to have a test case to use.

**Comment by pbeshai** [comment] 2016-11-17 14:16
Also, if you could specify which type of curve you're using, that would be great.

**Comment by danielverejan** [comment] 2016-11-17 14:35
Here's a JSFiddle https://jsfiddle.net/DanielVR/w1uhhnaL/
Couldn't load there the plugin so I guess you'll have to run it locally.
Path animation is in drawLine method, also there's a method(pathTween) from https://bl.ocks.org/mbostock/3916621 but it's very laggy with about 700ms delay

**Comment by pbeshai** [comment] 2016-11-21 15:14
Thanks! I'm looking into it. It's kind of tricky since the approach of having points merge into one another doesn't really work with a curved path (you get loops like you see in your example). I'll try some things out and let you know how it goes.

**Comment by pbeshai** [comment] 2016-11-21 15:29
The problem is that in my approach, I place points directly on top of each other to make them match in number before extending. This is fine in linear cases since a point on top of another looks the same, but doesn't work in curved cases as well. To fix it, instead of placing points directly on top of one another, I'd have to interpolate to a place in between two adjacent points and put the points there. I'll investigate the feasibility of this approach.

**Comment by danielverejan** [comment] 2016-11-21 15:37
Awesome, hope you can figure it out.

**Comment by gnarf** [comment] 2016-11-21 16:40
In the meantime, you could fork and rename the project `d3-shark-path` :)

(What a cool looking glitchy behavior I must say)

**Comment by pbeshai** [comment] 2016-11-21 17:30
I've got a solution that does this: (excuse the low frame rate of the GIF)

![interpolate_fix1](https://cloud.githubusercontent.com/assets/793847/20493303/310bf34c-afe6-11e6-9583-c0be80d2c322.gif)


Not perfect, but probably better. I'll play around a bit more and see what I can get

**Comment by danielverejan** [comment] 2016-11-21 17:46
Yeah this looks a lot better.

@gnarf Nice idea! The clients may like the 'sharper' look of their data.

**Comment by pbeshai** [comment] 2016-11-21 21:53
Closing this and moving further improvements to #10. The current state is available in v1.1.0.

**Closed** 2016-11-21 21:54 UTC

**Comment by pbeshai** [comment] 2017-07-05 15:27
FYI in v2.0.0, this should now be interpolated in an ideal way.

**Comment by danielverejan** [comment] 2017-07-06 06:58
Awesome, thank you for the work!
